# Generated by Django 5.0.7 on 2024-08-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=100)),
                ('city_district', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('external_url', models.URLField()),
            ],
        ),
    ]
